apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: enterprise-api
  namespace: data-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: enterprise-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kafka-consumer
  namespace: data-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-consumer
